# .github/workflows/run-tests.yml
name: run-tests

on:
  push:
  pull_request:

jobs:
  tests:
    name: php${{ matrix.php }} / laravel${{ matrix.laravel }} (stable)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.3', '8.4']
        laravel: ['11.*', '12.*']
        testbench: ['9.*', '10.*']
        exclude:
          - laravel: '11.*'
            testbench: '10.*' # TB 10 targets Laravel 12
          - laravel: '12.*'
            testbench: '9.*'  # TB 9 targets Laravel 11
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, dom, curl, json, pdo, sqlite, pdo_sqlite
          coverage: none
      - run: composer config minimum-stability stable
      - run: composer require "illuminate/contracts:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-progress
      - run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - run: php -r "echo 'APP_KEY=' . bin2hex(random_bytes(16)) . PHP_EOL;" >> .env
      - run: vendor/bin/pest --ci

  lowest-deps:
    name: php${{ matrix.php }} / laravel${{ matrix.laravel }} (prefer-lowest)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.3', '8.4']
        laravel: ['12.*']
        testbench: ['10.*']
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, dom, curl, json, pdo, sqlite, pdo_sqlite
          coverage: none
      - run: composer update --prefer-lowest --prefer-stable --no-interaction --no-progress
      - run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - run: php -r "echo 'APP_KEY=' . bin2hex(random_bytes(16)) . PHP_EOL;" >> .env
      - run: vendor/bin/pest --ci
